# Platform Settings
platform:
  pages:
    admin:
      home: /admin
      about: /about

# Common Server Settings
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: qxcmpAdmin
    key-store-type: PKCS12
    key-alias: qxcmp
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/javascript,text/html,text/xml,text/plain,text/css

# Spring Framework Settings
spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
  messages:
    basename: i18n/qxcmp, i18n/ValidationMessages
  data:
    rest:
      max-page-size: 100
  datasource:
    url: jdbc:mysql://localhost:3306/${platform.database.name}?useSSL=false
    username: ${platform.database.username}
    password: ${platform.database.password}
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
logging:
  file: logs/${platform.application.title}.log
logging.level.us.codecraft.webmagic: ERROR
logging.level.org.apache.http.client.protocol: ERROR